# Generated by Django 4.2.2 on 2023-09-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default_profile.png', upload_to='profile_pics/'),
        ),
    ]
